### PR TITLE
Show user current temperature, time of the city

### PR DESCRIPTION
**Pull request by rahulshah456**

### CODE REVIEW

**Comment by Sid200026** [comment]
When displaying the weather and time for a particular city, the results overlap with each other. An easy solution would be adding appropriate constraints on all four sides to prevent overlap. 

Also consider hiding the temperature and time ( have alpha as 0 ) till a valid city has been entered.

Apart from this all changes look good @rahulshah456 ....
Once you fix the above issues I will merge your PR

**Comment by rahulshah456** [comment]
Constraints Overlap issue fixed and results visibility hidden until check weather clicked.

**Comment by Sid200026** [comment]
One small issue still remains... when the user inputs a city which is not valid, time and temperature are still shown. Apart from these all other issues have been fixed @rahulshah456 .

**Comment by rahulshah456** [comment]
Fixed! , anything else...

**Comment by Sid200026** [comment]
Merged @rahulshah456 ....if you want to modify some other app or create a new one, create a new issue. I will closing the issue related to this PR.

**Pull request merged**
